"""Generate docs/security.md from the threat register and the measured red-team results.

The document is derived rather than written so it cannot drift from the code. A security document
nobody re-derives describes what someone once intended; this one describes what the harness
measured on the run whose results are committed beside it.
"""

from __future__ import annotations

import json
from pathlib import Path

from security.asi import STRUCTURAL, THREATS

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "docs" / "results" / "redteam.json"
OUT = ROOT / "docs" / "security.md"

PREAMBLE = """# Security

This file is generated by `scripts/build_security_doc.py` from `security/asi.py` and
`docs/results/redteam.json`. Editing it by hand is pointless — the next run overwrites it.
That is deliberate: a security document nobody re-derives is a description of what someone
once intended, and this one is a description of what the harness measured.

## The boundary

Four properties hold by construction rather than by policy, which is why they are stated
first and tested separately:

- No endpoint anywhere in the API buys, sells, lists or finances anything. `tests/test_api.py`
  reads the route table and fails if a transaction verb appears as a path segment.
- No tool in the agent registry has side effects. The Auditor blocks any run in which one is
  registered.
- The Advisor — the agent that writes the recommendation — is granted the empty set of tools.
- Queries run on a read-only connection and are refused before that if they are not plain selects.

## Authentication

Reads are public: the Land Department data is published, and requiring a login to look at open
data would be security theatre pointing the wrong way. What is protected is the surface that
*spends* something — creating a memo runs the agent crew, which costs model quota and CPU.

A caller proves identity at `POST /auth/token` and receives a token this service signed. The role
lives in the token's claims, so it is a statement the service made rather than one the caller
made. `api/auth.py` has the detail; the decoder pins one algorithm, checks the issuer, and
requires an expiry.

**This replaced a hole rather than filling a gap.** The role used to arrive in an
`X-Yieldmap-Role` header that the interface set from a dropdown, and the API believed it: a
stranger with curl could send `X-Yieldmap-Role: analyst` and write. The red-team attack meant to
catch that tested malformed role values instead, confirmed they degraded to viewer, and reported
the control held — a green tick on an open door. `rbac_bypass` now tries the bypass that worked,
and `tests/test_redteam.py` puts the old behaviour back to prove the attack would fail against it.

## Rate limits

Budgets bound one agent run. Rate limits bound how many a caller can start, which is a different
control: two hundred well-behaved runs spend a day's free-tier quota as completely as one runaway
loop. A token bucket per caller — keyed on the account when there is one, the client address
otherwise — allows 120 reads a minute, 12 questions a minute, and 6 memos an hour. Buckets live in
the process, which is exact on one instance and would need a shared counter on two.

## Threat register

The OWASP Agentic Security Initiative list, mapped onto this system. Every row that claims a
control names the attack in `security/redteam.py` that tries to defeat it.

| Threat | Where it lands here | What stops it | Attack | Held |
| --- | --- | --- | --- | --- |
"""

CLOSING = """
Each attack is a real attempt, not a mock: the poisoned document goes into a real index, the
forged message onto a real bus, the flood through a real crew run. A control that only holds
against a stub has not been tested.

## Secrets

Keys are read from the environment and never written to the repository.
`scripts/scan_secrets.py` runs in CI over every tracked file and **blocks** on a match — the only
audit here that blocks, because a key that reaches a public repository is already leaked and no
later commit un-leaks it. `tests/test_secret_scan.py` plants one of each credential shape to prove
the scanner would find it.

## Dependencies

`pip-audit` and `npm audit` run in CI and report as warnings rather than failures. Advisory data
changes daily and is outside this repository's control; a new advisory in a transitive dependency
should be visible and fixed, not turn an unrelated pull request red.

## Transport and browser policy

- A Content-Security-Policy is set per request in `web/proxy.ts` with a fresh nonce, so
  Next's own bootstrap runs and an injected inline script does not. Every route is rendered per
  request because a prerendered page has no request to take a nonce from.
- The browser only ever calls the app's own origin. `web/app/api/[...path]/route.ts` proxies to
  the analytics API, which means no cross-origin requests, no CORS to configure, and
  `connect-src 'self'` rather than a list of allowed hosts.
- `X-Frame-Options: DENY` and `frame-ancestors 'none'`; `X-Content-Type-Options: nosniff`.
- **One origin other than this one may run script**: `va.vercel-scripts.com`, which serves the
  Speed Insights collector. It is allowed because it adds no trust that was not already given —
  Vercel serves every byte of this application, so a compromise there reaches the page with or
  without the entry. That is the argument; "the measurement is useful" is not, because it would
  justify any script at all. Vercel Analytics was installed and removed on the same reasoning
  reversed: it counts visitors, this project holds no personal data, and a pageview total is not
  worth giving that up.

## Roles

Viewer, analyst, admin. The role arrives in a header the deployment's gateway sets; anything
unrecognised degrades to viewer rather than escalating. Creating a memo is the only write in the
application and requires the analyst role, enforced in the API rather than by hiding the button.
"""


def build() -> str:
    report = json.loads(RESULTS.read_text())
    verdicts = {o["id"]: o for o in report["outcomes"]}

    lines = [PREAMBLE.rstrip("\n")]
    for threat in THREATS + STRUCTURAL:
        outcome = verdicts.get(threat.attack_id or "")
        # A threat with no attack is an admission, not a pass: it renders as a dash so the
        # register cannot show an untested control the same way it shows a tested one.
        if outcome is None:
            held = "—"
        elif outcome["held"]:
            held = "yes"
        else:
            held = "**NO**"
        attack = threat.attack_id or "not attacked"
        lines.append(
            f"| **{threat.id}** {threat.name} | {threat.surface} | {threat.control} "
            f"| `{attack}` | {held} |"
        )

    lines += [
        "",
        "## What the harness measured",
        "",
        f"Run on {report['generated_at'][:10]}. "
        f"{report['controls_held']} of {report['attacks_run']} controls held.",
        "",
        "| Attack | Attempted | Outcome |",
        "| --- | --- | --- |",
    ]
    for outcome in report["outcomes"]:
        mark = "held" if outcome["held"] else "**FAILED**"
        lines.append(f"| `{outcome['id']}` | {outcome['attack']} | {mark} — {outcome['detail']} |")

    lines.append(CLOSING)
    return "\n".join(lines) + "\n"


def main() -> int:
    if not RESULTS.exists():
        print(f"{RESULTS.relative_to(ROOT)} is missing; run security.redteam first")
        return 1
    OUT.write_text(build())
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
