"""Render the source-reachability table in docs/datasets.md from the probe artefact.

The table used to be prose, typed by hand from a run someone had read. It drifted, which is the
predictable end of a hand-typed measurement: on 2026-09-07 the document called
`gateway.dubailand.gov.ae` reachable while `docs/results/source_probe.json` recorded ok=false and
a 404, and the ingest workflow listed it among the hosts it had found unreachable.

The rows here carry counts and observed statuses and nothing else. "Reachable" is a judgement, and
the two places that made it were using different definitions — one meant the host responded, the
other meant an address served what was asked for. Judgement belongs in the prose beneath the
table, where a reader can see it is a judgement.

    uv run python -m scripts.render_probe_table            # rewrite the table
    uv run python -m scripts.render_probe_table --check    # fail if it is out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent
PROBE = ROOT / "docs" / "results" / "source_probe.json"
DOC = ROOT / "docs" / "datasets.md"

BEGIN = "<!-- probe:begin -- generated by scripts/render_probe_table.py; do not edit by hand -->"
END = "<!-- probe:end -->"


def _short(path: Path) -> str:
    """A repository-relative path when it is one, and the whole path when it is not."""
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def _observed(row: dict[str, Any]) -> str:
    """What came back, as recorded: a status code, or the exception class that replaced one."""
    status = row.get("status")
    if status is not None:
        return str(status)
    error = str(row.get("error") or "")
    return error.split(":", 1)[0] or "no response"


def rows(report: dict[str, Any]) -> list[dict[str, Any]]:
    by_host: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for candidate in report["candidates"]:
        by_host[urlparse(candidate["url"]).netloc].append(candidate)

    out = []
    for host, candidates in sorted(by_host.items()):
        seen = Counter(_observed(c) for c in candidates)
        out.append(
            {
                "host": host,
                "tried": len(candidates),
                "answered": sum(1 for c in candidates if c.get("ok")),
                "observed": ", ".join(
                    f"{code} (×{n})" if n > 1 else code for code, n in sorted(seen.items())
                ),
            }
        )
    return out


def render(report: dict[str, Any]) -> str:
    measured = (
        f"Measured from a `{report['runner']}` runner at {report['generated_at']}, from "
        f"`docs/results/source_probe.json`. {report['n_reachable']} of {report['n_candidates']} "
        "addresses answered"
    )
    if "n_catalogues" in report:
        measured += (
            f"; {report['n_catalogues_reachable']} of {report['n_catalogues']} catalogues, which "
            f"is what the verdict (**{report['verdict']}**) is about."
        )
    else:
        # Printing "0 of 0 catalogues" for an artefact that predates the field would read as
        # "there are no catalogues" rather than "this run did not count them".
        measured += (
            f". Its `verdict` field says **{report['verdict']}**, but this artefact predates the "
            "catalogue-aware verdict and was computed under the old rule, which counted any "
            "address answering — reference documentation included. The next nightly run replaces "
            "it."
        )

    lines = [
        BEGIN,
        "",
        measured,
        "",
        "| Host | Addresses tried | Answered | What came back |",
        "|---|---|---|---|",
    ]
    for row in rows(report):
        lines.append(
            f"| `{row['host']}` | {row['tried']} | {row['answered']} | {row['observed']} |"
        )
    lines += ["", END]
    return "\n".join(lines)


def splice(doc: str, table: str) -> str:
    start, end = doc.find(BEGIN), doc.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{DOC} has no probe:begin/probe:end markers; add them around the table first"
        )
    return doc[:start] + table + doc[end + len(END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail rather than rewrite")
    args = parser.parse_args(argv)

    report = json.loads(PROBE.read_text())
    current = DOC.read_text()
    wanted = splice(current, render(report))

    if current == wanted:
        print(f"{_short(DOC)} matches {_short(PROBE)}")
        return 0
    if args.check:
        print(
            f"{_short(DOC)} no longer matches {_short(PROBE)}.\n"
            "Run: uv run python -m scripts.render_probe_table",
            file=sys.stderr,
        )
        return 1
    DOC.write_text(wanted)
    print(f"rewrote the table in {_short(DOC)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
